services:
  db:
    image: postgres:17.5
    container_name: 'aula-db'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: 'America/Sao_Paulo'
      PGTZ: 'America/Sao_Paulo'
    ports:
      - "0.0.0.0:5432:5432"
    volumes:
      - aula-db-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  aula-db-data: